logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    _org.springframework.web.servlet.HandlerMapping.Mappings: WARN


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

tmdb:
  api-key: 11111111111111
