logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    _org.springframework.web.servlet.HandlerMapping.Mappings: WARN


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

# tenemos que configurarle el mismo server para facilitar la configuración de Wiremock
# TMDB usa por defecto https pero eso requiere instalar un certificado en el servidor local y es más problemático
tmdb:
  api-key: 11111111111111
  base-url: http://localhost:9080

auth:
  base-url: http://localhost:9080