spring:
  application:
    name: ranking-service

  # base documental
  data:
    mongodb:
      uri: mongodb://capo:eyra@127.0.0.1:27019/peliculas?authSource=admin

  mongodb:
    embedded:
      version: 4.4.0

  # importante para que se active graphiql!
  graphql:
    graphiql:
      enabled: true

server:
  port: 9091
  error:
    include-message: always
    include-binding-errors: always

# Para activar el Trace
logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    _org.springframework.web.servlet.HandlerMapping.Mappings: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

tmdb:
  base-url: https://api.themoviedb.org/3

auth:
  base-url: http://192.168.0.103:9090