spring:
  # seguridad
  security:
    user:
      name: admin
      password: admin

  # base de datos posta
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/peliculas_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
