spring:
#  seguridad - si querés utilizar Basic Auth
#  security:
#    user:
#      name: admin
#      password: admin

  # base de datos posta
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/peliculas_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always

security:
  secret-key: fc11a8a903105382311a8c17a6595dbc3618b2c0d201c92bf56c7bbf1c4f55cb
  access-token-minutes: 300

# Para activar el Trace
#logging:
#  level:
#    root: TRACE