name: build-auth

on: 
  push:

    paths:
      - 'peliculas-microservice-auth/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./peliculas-microservice-auth
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew runOnGitHub

      - name: ls
        run: find * -print | grep xml

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: ./build/reports/**/*.xml, ./build/test-results/**/*.xml
          verbose: true