name: build-auth

on: 
  push:

    paths:
      - 'peliculas-microservice-auth/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./peliculas-microservice-auth
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew runOnGitHub

      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true