name: build-ranking

on: 
  push

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./peliculas-microservice-ranking
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start MongoDB
        run: docker compose -f "docker-compose.yml" up -d --build
        
      # Execute Gradle commands in GitHub Actions workflows
      - uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ./peliculas-microservice-ranking
          arguments: runOnGitHub

      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: false
          directory: peliculas-microservice-ranking
          flags: ranking
          verbose: true

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
