name: build-ranking

on: 
  push:

    paths:
      - 'peliculas-microservice-ranking/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./peliculas-microservice-ranking
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew runOnGitHub

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          directory: peliculas-microservice-ranking
          flags: ranking
          verbose: true