name: build-content

on: 
  push
  
jobs:
  gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./peliculas-microservice-content
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Start Redis
        run: docker compose -f "docker-compose.yml" up -d --build
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew runOnGitHub

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          directory: peliculas-microservice-content
          flags: content
          verbose: true

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
